# Generated by Django 4.2.4 on 2023-08-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iimtblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Populer_Blog',
            new_name='Popular_Blog',
        ),
        migrations.RemoveField(
            model_name='contacttb',
            name='create_at',
        ),
    ]
