# Generated by Django 4.2.4 on 2023-08-24 02:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iimtblog', '0002_rename_populer_blog_popular_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular_blog',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='regular_blog',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
